export const CURRENCY_OPTIONS = [
    { label: 'United States Dollar (USD)', value: 'USD' },
    { label: 'Euro (EUR)', value: 'EUR' },
    { label: 'Indian Rupee (INR)', value: 'INR' },
    { label: 'British Pound (GBP)', value: 'GBP' },
    { label: 'Canadian Dollar (CAD)', value: 'CAD' },
    { label: 'Australian Dollar (AUD)', value: 'AUD' },
    { label: 'Japanese Yen (JPY)', value: 'JPY' },
    { label: 'Swiss Franc (CHF)', value: 'CHF' },
    { label: 'Chinese Yuan (CNY)', value: 'CNY' },
    { label: 'Singapore Dollar (SGD)', value: 'SGD' },
    { label: 'Hong Kong Dollar (HKD)', value: 'HKD' },
    { label: 'New Zealand Dollar (NZD)', value: 'NZD' },
    { label: 'Swedish Krona (SEK)', value: 'SEK' },
    { label: 'South Korean Won (KRW)', value: 'KRW' },
    { label: 'Brazilian Real (BRL)', value: 'BRL' },
    { label: 'Russian Ruble (RUB)', value: 'RUB' },
    { label: 'South African Rand (ZAR)', value: 'ZAR' },
    { label: 'Turkish Lira (TRY)', value: 'TRY' },
    { label: 'Mexican Peso (MXN)', value: 'MXN' },
    { label: 'Saudi Riyal (SAR)', value: 'SAR' },
    { label: 'United Arab Emirates Dirham (AED)', value: 'AED' },
    { label: 'Andean Peso (ADP)', value: 'ADP' }, // Less common, but good to have breadth
    { label: 'Afghan Afghani (AFN)', value: 'AFN' },
    { label: 'Albanian Lek (ALL)', value: 'ALL' },
    { label: 'Armenian Dram (AMD)', value: 'AMD' },
    { label: 'Argentine Peso (ARS)', value: 'ARS' },
    { label: 'Bangladeshi Taka (BDT)', value: 'BDT' },
    { label: 'Bulgarian Lev (BGN)', value: 'BGN' },
    { label: 'Bahraini Dinar (BHD)', value: 'BHD' },
    { label: 'Bermudan Dollar (BMD)', value: 'BMD' },
    { label: 'Brunei Dollar (BND)', value: 'BND' },
    { label: 'Bolivian Boliviano (BOB)', value: 'BOB' },
    { label: 'Chilean Peso (CLP)', value: 'CLP' },
    { label: 'Colombian Peso (COP)', value: 'COP' },
    { label: 'Costa Rican Colón (CRC)', value: 'CRC' },
    { label: 'Czech Koruna (CZK)', value: 'CZK' },
    { label: 'Danish Krone (DKK)', value: 'DKK' },
    { label: 'Dominican Peso (DOP)', value: 'DOP' },
    { label: 'Egyptian Pound (EGP)', value: 'EGP' },
    { label: 'Hungarian Forint (HUF)', value: 'HUF' },
    { label: 'Indonesian Rupiah (IDR)', value: 'IDR' },
    { label: 'Israeli New Shekel (ILS)', value: 'ILS' },
    { label: 'Icelandic Króna (ISK)', value: 'ISK' },
    { label: 'Jamaican Dollar (JMD)', value: 'JMD' },
    { label: 'Jordanian Dinar (JOD)', value: 'JOD' },
    { label: 'Kenyan Shilling (KES)', value: 'KES' },
    { label: 'Kuwaiti Dinar (KWD)', value: 'KWD' },
    { label: 'Kazakhstani Tenge (KZT)', value: 'KZT' },
    { label: 'Sri Lankan Rupee (LKR)', value: 'LKR' },
    { label: 'Moroccan Dirham (MAD)', value: 'MAD' },
    { label: 'Malaysian Ringgit (MYR)', value: 'MYR' },
    { label: 'Nigerian Naira (NGN)', value: 'NGN' },
    { label: 'Norwegian Krone (NOK)', value: 'NOK' },
    { label: 'Nepalese Rupee (NPR)', value: 'NPR' },
    { label: 'Omani Rial (OMR)', value: 'OMR' },
    { label: 'Panamanian Balboa (PAB)', value: 'PAB' },
    { label: 'Peruvian Sol (PEN)', value: 'PEN' },
    { label: 'Philippine Peso (PHP)', value: 'PHP' },
    { label: 'Pakistani Rupee (PKR)', value: 'PKR' },
    { label: 'Polish Złoty (PLN)', value: 'PLN' },
    { label: 'Qatari Riyal (QAR)', value: 'QAR' },
    { label: 'Romanian Leu (RON)', value: 'RON' },
    { label: 'Thai Baht (THB)', value: 'THB' },
    { label: 'Taiwan Dollar (TWD)', value: 'TWD' },
    { label: 'Ukrainian Hryvnia (UAH)', value: 'UAH' },
    { label: 'Venezuelan Bolívar (VES)', value: 'VES' },
    { label: 'Vietnamese Đồng (VND)', value: 'VND' },
    { label: 'West African CFA Franc (XOF)', value: 'XOF' },
];
